name: vscode
services:
  main_app:
    cpu_shares: 90
    command: []
    deploy:
      resources:
        limits:
          memory: 15767M
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: APP_HOST
          description:
            en_us: Host to listen on, defaults to '0.0.0.0'
        - container: APP_PORT
          description:
            en_us: "Port to listen on. If 0 is passed a random free port is picked [default: 8000]"
    image: ghcr.io/teneff/casaos-vscode:main
    labels:
      icon: https://icon.casaos.io/main/all/casaos-vscode.png
    ports:
      - target: 8000
        published: "8122"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
    container_name: ""
x-casaos:
  author: Teneff
  category: IDE
  hostname: "vscode"
  icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAABVlBMVEVHcEwAcLMkrvMAe8MAfMIAer8Hg8sjqfIipvIOidIFg8sAcbQAg9AAfcUAfMIjqfIAcbMAcrQFi9UAdLcAcrQAcrYAidIAc7giqPIAjtUAitIAcrQAhtEAcLMAhNAip/EAg80Ah9EAg9AAiNIAhNAAiNIGi9QjqPIfnvAAfcUAhtEmsvMAfs4goe8msvMfnvAAf88Aj9UAebsAcrYAeb0AfMUmsvMAe7wAe8Ualeodn+oAfL0jo/IAhtEjqfIho/Eip/IlsPMAd7kgoPEAidIAbbAAgs8AjdQkrPIkrvMAe7wAhNAAjtQAgc8Adrgms/QjqvIipvEgofEAebsAbrEAg9AAkNUAa68AdLYAi9Mkq/IAdbchpPEgn/AAfM0lsvMAcrUBdssAb7MCec0AdrcAf84AhdElsfQAZ6wDdbwcm+0AdLkhquwDeb8gp+sbmOsBfsYUkt1kR7lhAAAAPHRSTlMA5N1YCT4OHd8ENXnVKRg5w6hI0WkfHkqD5XGXxO3lJ7ODle9m+aWk54Cf5/jxkpLvyPX52Kfy7ufW2vkg6HZJAAADhklEQVRYw6WXWVvaQBSGB5Gwt+wqWwEBN3Cptlb7YEsKLoDQChJwhSDWpVj9/zedSSBkZkJN4vtwyfdyDjk5yQCgAVt6d2r2A9DNzFZp8FLTrzB+KdUfnw9rOhVW33YJCgZ/apCV1fdWrXn7x9JYoF3BLH2F+RKLBNc19KmtLGhQMKGSANtCApFa7bNqxbtPYr7Otu4lgaBYZdTk/bGSTHCdl6jl87Mq8k5XvVQXYTuYIJ+/XlExfl4pLwh+5zFUjF9dgq127p80CoyG+psEvu36WwRw/FiM886joiAQjNsU8tNLRL56zj8+4fkj4X/eaDbngtP0+LE3SoIjDPhFk6OJSAeI8XOzJNUW780ekQLPXFNkw4ONn7vKVgluNkO2KVJgHOXxNpyuKgVr8FnNlGCcbzYrywFp/Oh81WUCwDx1iAMqMpqVDZOQN3lvaEJ+oCQIVzDmkvAWnzG0zkkMPqE/WuAMH8hpphIBY6TTaREKr1gaJTiDUxTDDRVHhGvwSDFm0+0HI8EZDrrgacxwUMndc0VepriJ2KXLoyQATKKNcdAecEIRQ4V3ZjweZstPHHHo4ylc0e7zYhEIqfzJAmANzhOG8iMqAioidmxvkoK90Y2bJA0F2AYsQl6+KNjDGa+eOcLQfubvOLcTqBUAT7SA097ftFNr/z+CGcM+YSik4hoERsMd3ycNhZjqFnyRInfHPVMGh4cUfMcZbc8I3xgacjjzceZ1wbR9k+cbyHA3yJGk0s7XBEyIR0wy5ORtmC2/cITt2RhSRIb7MmWYH+86BYFfyqMSoGFrnhTc3kq7jhY4XY0GZgj5jdFbirBpksBVxICLFw1lmeA2FxXbIAUXAM+7hkvVUaZICW2YLRc4wCDPh0a3vi1MCfZPURu0wGiQlS97sIRPaaJJq9nyDQfdRJzIsPwhgRgtOM4kbLQAPkVQvIhtLjQey/skx/2eI0sLgM3FcbLFKz3eE1S+37t6UBAAv89uUnrBiGeOMfpXvZ6iYOIrTnCdEHSh4ATjlZes5DolONEkAMZoX4YOAfA4CMEPHBWvumPDlS4BHEpJ0EOCSzmLak47/tioACj4i+UvZ1UeOK5ESEF2jVF34mISoqDb7coE2QWP6lMTE8+QgsUFTec261IGdSAJFtc0nxyT62OBjrhw9IWC3sPlg0Xv6dnj6HZfLndh3KpPYLWld3bIX/8HDVWSIvqyEAcAAAAASUVORK5CYII=
  description:
    en_us: The Visual Studio Code Server is a service you can run on a remote development machine, like your desktop PC or a virtual machine (VM). It allows you to securely connect to that remote machine from anywhere through a local VS Code client, without the requirement of SSH.
  tagline:
    en_us: The Visual Studio Code Server is a service you can run on a remote development machine, like your desktop PC or a virtual machine (VM). It allows you to securely connect to that remote machine from anywhere through a local VS Code client, without the requirement of SSH.
  developer: https://github.com/Teneff/casaos-vscode
  index: /
  port_map: "8122"
  scheme: http
  store_app_id: magical_rodriguez
  title:
    custom: Visual Studio Code
